config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  
  devise_for :users,
    controllers: {
      sessions: 'users/sessions'
    }

  # get 'movies/selected_patterns'
  # get 'movies/index'
  # get 'movies/new'
  # get 'movies/edit'

  # resources :patterns do
  #   member do
  #     get 'movies/next_movies'
  #     resources :movies, except: %i(index new edit)
  #   end
  # end

  resources :patterns

  get 'movies/selected_patterns', as: :selected_patterns
  
  get 'movies/next_movies', as: :next_movies

  # get 'movies/selected_movies'
  # post 'movies/add'
  # delete 'movies/remove'
  # patch 'movies/take_out'
  # put 'movies/take_out'

  resources :movies

  post 'selected_movies/add'
  resources :selected_movies

  resources :logs

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # addアクションのみCSRFの対策を除外する。
  protect_from_forgery except: [:add]
  before_action :logged_in_user, only: %i(selected_movies add)
  before_action :set_movie, only: %i(edit update destroy)

  # GET /resource/selected_patterns
  def selected_patterns
    @movies = Movie.where(pattern_id: params[:id]).order(:order_number)
    @movie_size = Movie.where(pattern_id: params[:id]).size
    @pattern = Pattern.find(params[:id])
    @pattern_size = Pattern.all.size
  end

  # GET /resource/index
  def index
    @movies = Movie.all.order(:pattern_id, :order_number, :id).group_by(&:pattern_id)
  end

  # GET /resource/show
  def show

  end

  # GET /resource/new
  def new
    @movie = Movie.new
  end

  # POST /resource/create
  def create
    # @patterns = Pattern.all.order(:id)
    # @pattern = Pattern.find(3)
    movie = Movie.new(movie_params)
    youtube_url = params[:movie][:youtube_url]
    youtube_mid = youtube_url.last(11)
    url = "https://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=#{youtube_mid}&format=json"
    # url = URI.encode url
    uri = URI.parse url
    require "net/http"
    json = Net::HTTP.get(uri)
    if valid_json?(json)
      movie_json = JSON.parse(json)
      movie = Movie.new({
        title: movie_json["title"],
        thumbnail_url: movie_json["thumbnail_url"],
        youtube_mid: youtube_mid,
        youtube_url: "https://youtu.be/#{youtube_mid}",
        author_name: movie_json["author_name"],
        text: params[:movie][:text]
      })
      if movie.save
        flash.now[:success] = "動画を追加しました。"
        redirect_to movies_path
      end
    else
      flash.now[:danger] = "URLが正しくありません。"
      redirect_to movies_path
    end
  end

  # GET /resource/edit
  def edit
    # @movie = Movie.find(params[:id]) 
  end

  # PUT /resource
  def update
    # @movies = Movie.all
    # @movie = Movie.find(params[:id])
    youtube_url = params[:movie][:youtube_url]
    youtube_mid = youtube_url.last(11)
    url = "https://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=#{youtube_mid}&format=json"
    # url = URI.encode url
    uri = URI.parse url
    require "net/http"
    json = Net::HTTP.get(uri)
    if valid_json?(json)
      if movie_json = JSON.parse(json)
        @movie.update ({
          title: movie_json["title"],
          thumbnail_url: movie_json["thumbnail_url"],
          youtube_mid: youtube_mid,
          youtube_url: "https://youtu.be/#{youtube_mid}",
          author_name: movie_json["author_name"],
          text: params[:movie][:text]
        })
      end
      flash[:success] = "動画を更新しました。"
      redirect_to movies_path
    else
      flash[:danger] = "URLが正しくありません。"
      redirect_to movies_path
    end
  end

  # DELETE /resource
  def destroy
    # @movie = Movie.find(params[:id])
    if @movie.destroy
      flash[:success] = "動画『#{@movie.title}』を削除しました。"
      redirect_to movies_path
    end
  end

  def next_movies
    @movies = Movie.where(pattern_id: params[:id]).order(:order_number)
    @movie_size = Movie.where(pattern_id: params[:id]).size
    @pattern = Pattern.find(params[:id])
    @pattern_size = Pattern.all.size
  end

  def selected_movies
    @movies = Movie.where(selected: false).order(:id)
    @selected_movies = Movie.where(selected: true).order(:pattern_id, :order_number)
  end


  private

    def movie_params
      params.require(:movie).permit(:youtube_url, :text)
    end

    def valid_json?(json)
      JSON.parse(json)
      return true
    rescue JSON::ParserError => e
      return false
    end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/ update.js.erb
$('.modal-backdrop').remove();
$('body').removeClass('modal-open');
$('body').css('padding-right', '0');
$('#admin-main__content').html('<%= j(render 'index') %>');

$("#flash_messages").removeClass();
<% flash.each do |msg_type, msg| %>
  $('#flash_messages').html('<a href="#" class="close" data-dismiss="alert">×</a><%= msg %>');
  $('#flash_messages').addClass('alert alert-<%= msg_type %>');
  $('#flash_messages').show();
<% end %>

setTimeout("$('#flash_messages').fadeOut('slow')", 4000);

app/views/movies/__selected_movies.html.erb
<div class="container movie-selected">

  <div class="align-top"><%= render 'shared/flash_messages' %></div>

  <% provide(:title, '面談動画一覧') %>

  <div style="text-align: center;">
    <h1><%= "面談動画選択" %></h1>
  </div>

  <hr>

  <!-- User一覧をリスト表示 -->
  <h4>Movie</h4>

  <table id="list" class="table border" width="1000">
    <tr style="text-align: center;">
      <th>No.</th>
      <th>タイトル</th>
    </tr>
    <% number = 0 %>
    <!--% Array(@movies).each do |movie| %-->
    <% @movies.each do |movie| %>
      <!-- rowにドラッグ可能(draggable)属性を指定 -->
      <% number += 1 %>
      <tr class="item" draggable="true" id="<%= movie.id %>">
        <td><%= number %></td>
        <td><%= movie.title %></td>
      </tr>
    <% end %>
  </table>

  <br>

  <!-- SelectedUser一覧をリスト表示 -->
  <h4>SelectedMovie</h4>

  <table class="table border" width="1000">
    <tr>
      <!-- ドロップエリア -->
      <td colspan="6" id="dropzone" class="dropzone"></td>
    </tr>

    <tr style="text-align: center;">
      <th>No.</th>
      <th>タイトル</th>
      <th>パターン</th>
      <th>表示順</th>
      <th></th>
      <th></th>
    </tr>
    <!--% Array(@selected_movies).each do |selected_movie| %-->
    <% number = 0 %>
    <% @selected_movies.each do |selected_movie| %>
      <% number += 1 %>
      <tr>
        <!--
        <td>< %= selected_movie.movie_id %></td>
        <td>< %= Movie.find(selected_movie.movie_id).title %></td>
        <td>< %= selected_movie.selected %></td>
        -->
        <td><%= number %></td>
        <td><%= selected_movie.title %></td>
        <td style="text-align: center;"><%= selected_movie.pattern_id %></td>
        <td style="text-align: center;"><%= selected_movie.order_number %></td>
        <td>
          <%= link_to "編集", edit_movie_path(selected_movie), remote: true, class: "btn btn-success" %>
        </td>
        <td>
          <%= link_to '戻す', movies_remove_path(id: selected_movie.id),
              class: "btn btn-secondary",
              method: :delete,
              remote: true,
              data: { confirm: "『#{selected_movie.title}』を選択を戻してよろしいですか？",
                      cancel: 'キャンセル',
                      commit: '戻す'
                    }, title: '戻し確認'
          %>
        </td>
      </tr>
    <% end %>
  </table>

</div>


<script>

    $(function () {

        // dropzoneの表示テキストを初期化
        initDropzone();

        // listテーブルのitem行が操作された時のリスナーを設定
        items = document.getElementById('list').getElementsByClassName('item');

        Array.prototype.forEach.call(items, function (item) {
            $(item).on('dragstart', onDragStart);
            $(item).on('dragend', onDragEnd);
        });

        // dropzoneのリスナーを設定
        var $dropzone = $('#dropzone')
            .on('dragover', onDragOver)
            .on('dragenter', onDragEnter)
            .on('dragleave', onDragLeave)
            .on('drop', onDrop);

        // dropzoneの表示テキストを指定
        function initDropzone() {
            $('#dropzone').text("ここにドロップできます。");
        }

        function startDropzone() {
            $('#dropzone').text("ドラッグ中。");
        }

        function endDropzone(title) {
            $('#dropzone').text(title + "をドロップしました。");
        }

        // ドロップ時の処理
        // (1) ドロップされた行のidをPOSTする
        // (2) 成功したらリダイレクトする
        // (3) 失敗したらダイアログを表示する
        function doAction(id) {
            $.ajax({
                url: "<%= selected_movies_add_path %>",
                type: "POST",
                data: {
                    id: id
                },
                dataType: "html",
                success: function (data) {
                    //alert("success");

                    // dataにドラッグ＆ドロップした
                    // Movieのid, titleがjson形式で
                    // 渡される
                    console.log(data);
                    // {"id":1,"name":"Yamada Taro"}

                    // 暫定的にページを再読込
                    location.href = "<%= selected_movies_path %>"
                },
                error: function (data) {
                    alert("errror");
                }
            });
        }

        // ドラッグ＆ドロップ操作
        function onDragStart(e) {
            // puts 'onDragStart';
            var id = e.originalEvent.target.id;
            var name = e.originalEvent.target.cells[1].innerHTML;
            e.originalEvent.dataTransfer.setData('id', id);
            e.originalEvent.dataTransfer.setData('title', title);
            addDraggingEffect();
            startDropzone();
        }

        function onDragEnter(e) {
            // puts 'onDragEnter';
            addEnterEffect();
        }

        function onDragLeave(e) {
            // puts 'onDragLeave';
            removeEnterEffect();
        }

        function onDragOver(e) {
            // puts 'onDragOver';
            e.preventDefault();
        }

        function onDragEnd(e) {
            // puts 'onDragEnd';
            resetAllEffect();
        }

        function onDrop(e) {
            // puts 'onDrop';
            e.preventDefault();
            var id = e.originalEvent.dataTransfer.getData('id');
            var title = e.originalEvent.dataTransfer.getData('title');
            endDropzone(title);
            doAction(id);
        }

        function addDraggingEffect() {
            // puts 'addDraggingEffect';
            $dropzone.addClass('dragging');
        }

        function removeDraggingEffect() {
            // puts 'removeDraggingEffect';
            $dropzone.removeClass('dragging');
            initDropzone();
        }

        function addEnterEffect() {
            // puts 'addEnterEffect';
            $dropzone.addClass('dragenter');
        }

        function removeEnterEffect() {
            // puts 'removeEnterEffect';
            $dropzone.removeClass('dragenter');
        }

        function resetAllEffect(e) {
            // puts 'resetAllEffect';
            removeDraggingEffect();
            removeEnterEffect();
        }

    });

</script>


<style>

  .dropzone p {
    margin: 0;
    padding: 0;
    background-color: #0000E9;
  }

  .dropzone.small {
    height: 40px;
  }

  .dropzone {
    border: 1px solid #555;
    margin-top: 5px;
    /*width: 246px;*/
    min-height: 100px;
    font-size: 12px;

    text-align: center;
    line-height: 100px;

    color: gray;
    background-color: ghostwhite;
    border-color: gray;
  }

  .dragging {
    color: rgba(0, 0, 0, .4);
    background-color: rgba(0, 0, 255, .1);
    border-color: rgba(0, 0, 255, .3);
  }

  .dragging:after {
  }

  .dragenter {
    border-color: rgba(255, 0, 0, .3);
    background-color: rgba(255, 0, 0, .1);
  }

</style>

app/views/movies/_edit.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header movie__modal-header">
      <div class="col-10 offset-1">
        <h3 class="modal-title">面談動画編集</h3>
      </div>
      <button type="button" class="btn-close" aria-label="close" data-bs-dismiss="modal"></button>
    </div>
    <div class="modal-body movie__modal-body ">
      <div class="col col-md-10 offset-1">
        <div class="edit-movies">
          <div class="movies__form">
            <%= form_with(model: @movie, remote: true) do |f| %>
              <div class="movies__input">
                <div class="movie__form-group">
                  <%= f.label :title, "タイトル：" %>
                  <%= @movie.title %>
                </div>
                <!--
                <div class="movie__form-group">
                  < %= f.label :youtube_url, "YouTubeのURL：" %>
                  < %= f.text_field :youtube_url, placeholder: 'URLを入力してください。', class: "form-control" %>
                  < %= @movie.youtube_url %>
                </div>
                -->
                <div class="movie__form-group">
                  <%= f.label :text, "コメント" %>
                  <%= f.text_area :text, placeholder: '動画説明やコメントを入力できます。（300文字以内）',
                                          size: "8x4", class: "form-control memo" %>
                </div>
              </div>
              <div class="movie__form-group">
                <div class="btn-sub-can">
                  <%= f.submit "更新", name: nil, class: "btn btn-success btn-edit", data: { disable_with: '送信中' } %>
                  <button type="button" class="btn btn-outline-dark bg-light btn-edit" data-bs-dismiss="modal">
                    キャンセル
                  </button>
                </div>
              </div>
            <% end %>
          </div> 
          <!--
          <div class="col-8 pr-0">
            <div class="row">
              <img src="<%= @movie.thumbnail_url %>" 
                class="bd-placeholder-img thumbnail align-items-center img-center" alt="サムネイル"><br>
            </div>
          </div>
          -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_index.html.erb
<div style="text-align: center;">
  <h1><%= "面談動画一覧" %></h1>
</div>

<div class="text-end" style="margin-right: 20px;">
  <%= link_to "新規登録", new_movie_url, remote: true, class: "btn btn-primary movie__link" %>
</div>

<section class="movie container" id="index-movies" style="text-align: center; max-width: 500px;">
  <% @movies.each do |pattern_id, movies| %>
    <% if pattern_id == 0 %>
      <h3><%= "未分類" %></h3>
    <% else %>
      <h4><%= Pattern.find(pattern_id).name %></h4>
    <% end %>
    <% movies.each do |movie| %>
      <div class="movie__inner">
        <div class="movie__title">
          <%= movie.title.truncate(50) %>
          <div class="display-off-text"></div>
        </div>
        <div class="movie__iframe embed-responsive embed-responsive-21by9">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= movie.youtube_mid %>"
                  frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                  style="height: 169px;" allowfullscreen>
          </iframe>
        </div>
        <div class="movie__text">
          <span class="movie__text__title">コメント</span>
          <p><%= movie.text %></p>
        </div>
        <br>
        <div class="movie__edit">
          <%= link_to "編集", edit_movie_path(movie), remote: true, class: "btn btn-success" %>
          <%= link_to '削除', movie_path(movie),
              class: "btn btn-danger",
              method: :delete,
              remote: true,
              data: { confirm: "『#{movie.title}』を削除してよろしいですか？",
                      cancel: 'キャンセル',
                      commit: '削除する'
                    }, title: '削除確認'
          %>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/movies/_new.html.erb
<div class="modal-dialog modal-lg modal-dialog-center;">
  <div class="modal-content">
    <div class="modal-header movie__modal-header">
      <div class="col-10 offset-1">
        <h3 class="modal-title">面談動画新規登録</h3>
      </div>
      <button type="button" class="btn-close" aria-label="close" data-bs-dismiss="modal"></button>
    </div>

    <div class="modal-body movie__modal-body">
      <div class="col-10 offset-1">
        <div class="conteiner">
          <div class="movies__form">
            <%= form_with model: @movie, remote: true do |f| %>
              <div class="movies__input">
                <%= f.label :youtube_url, "YouTubeのURL"%><br>
                <%= f.text_field :youtube_url, placeholder: 'URLを入力してください。', id: "modal-new-foucus", class: "form-control", required: true %><br>

                <%= f.label :text, "コメント" %><br>
                <%= f.text_area :text, placeholder: '動画説明やコメントを入力できます。（300文字以内）',
                                          size: "20x7", class: "form-control memo" %>
              </div>
              <br>
              <%= f.submit class: "btn btn-primary", data: { disable_with: '送信中' } %>
              <button type="button" class="btn btn-outline-dark bg-light btn-edit" data-bs-dismiss="modal">
                キャンセル
              </button>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/movies/_next_movies.html.erb
<h3><%= @pattern.name %></h3>

<% if @movie_size == 0 %>
  <div style="margin-top: 150px; font-size: 30px;">ただいま、準備中です。</div>
  <div style="font-size: 30px;">暫くお待ち下さい！</div>
<% else %>
  <% @movies.each do |movie|%>
    <div class="movie__inner">
      <div class="movie__title">
        <%= movie.title.truncate(50) %>
        <div class="display-off-text"></div>
      </div>
      <div class="movie__iframe embed-responsive embed-responsive-21by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= movie.youtube_mid %>"
                frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                style="height: 169px;" allowfullscreen>
        </iframe>
      </div>
      <div class="movie__text">
        <span class="movie__text__title">コメント</span>
        <p><%= movie.text %><p>
      </div>
    </div>
  <% end %>
<% end %>

<% if @pattern.id != 1 %>
  <button type="button" class="btn-square-little-rich">
    <%= link_to '< 前の動画', next_movies_path(id: @pattern.id - 1), remote: true, style: "text-decoration: none;" %>
  </button>
<% end %>

<% if (@pattern.id + 1) <= @pattern_size %>
  <button type="button" class="btn-square-little-rich">
    <%= link_to '次の動画 >', next_movies_path(id: @pattern.id + 1), remote: true, style: "text-decoration: none;" %>
  </button>
<% end %>

app/views/movies/edit.js.erb
$("#edit-movie").html("<%= escape_javascript(render 'edit') %>");
$("#edit-movie").modal("show");

app/views/movies/index.html.erb
<div class="container movie-index">

  <div class="align-top"><%= render 'shared/flash_messages' %></div>

  <% provide(:title, '面談動画一覧') %>

  <div class="conteiner">
    <div id="movie__index">
      <%= render 'index' %>
    </div>
  </div>

</div>

<div id="edit-movie" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="new-movie" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/movies/new.html.erb
<div style="text-align: center;">
  <h2>動画投稿画面</h2>
</div>

<div class="conteiner">
  <div class="col-10 offset-1"> 
    <div class="movies__form">
      <%= form_with(model: @movie, local: true) do |f| %>
        <div class="movies__input">
          <%= f.label :youtube_url, "YouTubeのURL"%><br>
          <%= f.text_field :youtube_url, placeholder: 'URLを入力してください。', style: "width:300px" %><br>
          <%= f.label :text, "コメント" %><br>
          <%= f.text_area :text, placeholder: '動画説明やメッセージを入力できます。（300文字以内）',
                                  size: "20x7", class: "form-control memo"
          %>
        </div>
        <%= f.submit '投稿する', class: "btn btn-primary" %><br><br>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.js.erb
$("#new-movie").html("<%= escape_javascript(render 'new') %>");
$("#new-movie").modal("show");

app/views/movies/selected_movies.html.erb
<div class="container movie-selected">

  <div class="align-top"><%= render 'shared/flash_messages' %></div>

  <% provide(:title, '面談動画一覧') %>

  <div style="text-align: center;">
    <h1><%= "面談動画選択" %></h1>
  </div>

  <hr>

  <!-- User一覧をリスト表示 -->
  <h4>Movie</h4>

  <table id="list" class="table border" width="1000">
    <tr style="text-align: center;">
      <th>No.</th>
      <th>タイトル</th>
    </tr>
    <% number = 0 %>
    <!--% Array(@movies).each do |movie| %-->
    <% @movies.each do |movie| %>
      <!-- rowにドラッグ可能(draggable)属性を指定 -->
      <% number += 1 %>
      <tr class="item" draggable="true" id="<%= movie.id %>">
        <td><%= number %></td>
        <td><%= movie.title %></td>
      </tr>
    <% end %>
  </table>

  <br>

  <!-- SelectedUser一覧をリスト表示 -->
  <h4>SelectedMovie</h4>

  <table class="table border" width="1000">
    <tr>
      <!-- ドロップエリア -->
      <td colspan="6" id="dropzone" class="dropzone"></td>
    </tr>

    <tr style="text-align: center;">
      <th>No.</th>
      <th>タイトル</th>
      <th>パターン</th>
      <th>表示順</th>
      <th></th>
      <th></th>
    </tr>
    <!--% Array(@selected_movies).each do |selected_movie| %-->
    <% number = 0 %>
    <% @selected_movies.each do |selected_movie| %>
      <% number += 1 %>
      <tr>
        <!--
        <td>< %= selected_movie.movie_id %></td>
        <td>< %= Movie.find(selected_movie.movie_id).title %></td>
        <td>< %= selected_movie.selected %></td>
        -->
        <td><%= number %></td>
        <td><%= selected_movie.title %></td>
        <td style="text-align: center;"><%= selected_movie.pattern_id %></td>
        <td style="text-align: center;"><%= selected_movie.order_number %></td>
        <td>
          <%= link_to "編集", edit_movie_path(selected_movie), remote: true, class: "btn btn-success" %>
        </td>
        <td>
          <%= link_to '戻す', movies_remove_path(id: selected_movie.id),
              class: "btn btn-secondary",
              method: :delete,
              remote: true,
              data: { confirm: "『#{selected_movie.title}』を選択を戻してよろしいですか？",
                      cancel: 'キャンセル',
                      commit: '戻す'
                    }, title: '戻し確認'
          %>
        </td>
      </tr>
    <% end %>
  </table>

</div>


<script>

    $(function () {

        // dropzoneの表示テキストを初期化
        initDropzone();

        // listテーブルのitem行が操作された時のリスナーを設定
        items = document.getElementById('list').getElementsByClassName('item');

        Array.prototype.forEach.call(items, function (item) {
            $(item).on('dragstart', onDragStart);
            $(item).on('dragend', onDragEnd);
        });

        // dropzoneのリスナーを設定
        var $dropzone = $('#dropzone')
            .on('dragover', onDragOver)
            .on('dragenter', onDragEnter)
            .on('dragleave', onDragLeave)
            .on('drop', onDrop);

        // dropzoneの表示テキストを指定
        function initDropzone() {
            $('#dropzone').text("ここにドロップできます。");
        }

        function startDropzone() {
            $('#dropzone').text("ドラッグ中。");
        }

        function endDropzone(title) {
            $('#dropzone').text(title + "をドロップしました。");
        }

        // ドロップ時の処理
        // (1) ドロップされた行のidをPOSTする
        // (2) 成功したらリダイレクトする
        // (3) 失敗したらダイアログを表示する
        function doAction(id) {
            $.ajax({
                url: "<%= selected_movies_add_path %>",
                type: "POST",
                data: {
                    id: id
                },
                dataType: "html",
                success: function (data) {
                    //alert("success");

                    // dataにドラッグ＆ドロップした
                    // Movieのid, titleがjson形式で
                    // 渡される
                    console.log(data);
                    // {"id":1,"name":"Yamada Taro"}

                    // 暫定的にページを再読込
                    location.href = "<%= selected_movies_path %>"
                },
                error: function (data) {
                    alert("errror");
                }
            });
        }

        // ドラッグ＆ドロップ操作
        function onDragStart(e) {
            // puts 'onDragStart';
            var id = e.originalEvent.target.id;
            var name = e.originalEvent.target.cells[1].innerHTML;
            e.originalEvent.dataTransfer.setData('id', id);
            e.originalEvent.dataTransfer.setData('title', title);
            addDraggingEffect();
            startDropzone();
        }

        function onDragEnter(e) {
            // puts 'onDragEnter';
            addEnterEffect();
        }

        function onDragLeave(e) {
            // puts 'onDragLeave';
            removeEnterEffect();
        }

        function onDragOver(e) {
            // puts 'onDragOver';
            e.preventDefault();
        }

        function onDragEnd(e) {
            // puts 'onDragEnd';
            resetAllEffect();
        }

        function onDrop(e) {
            // puts 'onDrop';
            e.preventDefault();
            var id = e.originalEvent.dataTransfer.getData('id');
            var title = e.originalEvent.dataTransfer.getData('title');
            endDropzone(title);
            doAction(id);
        }

        function addDraggingEffect() {
            // puts 'addDraggingEffect';
            $dropzone.addClass('dragging');
        }

        function removeDraggingEffect() {
            // puts 'removeDraggingEffect';
            $dropzone.removeClass('dragging');
            initDropzone();
        }

        function addEnterEffect() {
            // puts 'addEnterEffect';
            $dropzone.addClass('dragenter');
        }

        function removeEnterEffect() {
            // puts 'removeEnterEffect';
            $dropzone.removeClass('dragenter');
        }

        function resetAllEffect(e) {
            // puts 'resetAllEffect';
            removeDraggingEffect();
            removeEnterEffect();
        }

    });

</script>


<style>

  .dropzone p {
    margin: 0;
    padding: 0;
    background-color: #0000E9;
  }

  .dropzone.small {
    height: 40px;
  }

  .dropzone {
    border: 1px solid #555;
    margin-top: 5px;
    /*width: 246px;*/
    min-height: 100px;
    font-size: 12px;

    text-align: center;
    line-height: 100px;

    color: gray;
    background-color: ghostwhite;
    border-color: gray;
  }

  .dragging {
    color: rgba(0, 0, 0, .4);
    background-color: rgba(0, 0, 255, .1);
    border-color: rgba(0, 0, 255, .3);
  }

  .dragging:after {
  }

  .dragenter {
    border-color: rgba(255, 0, 0, .3);
    background-color: rgba(255, 0, 0, .1);
  }

</style>

app/views/movies/selected_patterns.html.erb
<div style="text-align: center;">
  <h1><i class="fas fa-video"></i>&nbsp;<%= "面談動画" %></h1>
</div>

<div class="container">
  <div id="next-movies" class="movie" style="text-align: center; max-width: 500px;">
    <%= render 'next_movies' %>
  </div>
</div>

app/views/movies/show.html.erb
<div style="text-align: center;">
  <h2><i class="fas fa-video"></i>&nbsp;<%= "面談動画" %></h2>
</div>

<div class="movie container" style="text-align: center;">
  <div class="row">
    <div id="movie__index" class="col align-self-center;">
      <div id="next-movies">
        <%= render 'next_movies' %>
      </div>
    </div>
  </div>
</div>