config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  
  devise_for :users,
    controllers: {
      sessions: 'users/sessions'
    }

  # get 'movies/selected_patterns'
  # get 'movies/index'
  # get 'movies/new'
  # get 'movies/edit'

  # resources :patterns do
  #   member do
  #     get 'movies/next_movies'
  #     resources :movies, except: %i(index new edit)
  #   end
  # end

  resources :patterns

  get 'movies/selected_patterns', as: :selected_patterns
  
  get 'movies/next_movies', as: :next_movies

  # get 'movies/selected_movies'
  # post 'movies/add'
  # delete 'movies/remove'
  # patch 'movies/take_out'
  # put 'movies/take_out'

  resources :movies

  post 'selected_movies/add'
  resources :selected_movies

  resources :logs

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @patterns = Pattern.all.order(:id)
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/top.html.erb
<div class="container main top-main">

  <div class="align-top"><%= render 'shared/flash_messages' %></div>

  <div class="row justify-content-center;">
    <%# <div class="top-message" style="text-align: center;">
      <h1>面談練習アプリ</h1>
    </div> %>

    <div style="text-align: center;">
      <h2>面談動画パターン選択</h2><br>
      <% @patterns.each do |pattern| %>
        <div class="btn-group">
          <!-- <button type="button" class="btn-solid-silver"> -->
          <button type="button" class="btn-solid">
            <%= link_to "#{pattern.name}", selected_patterns_path(id: pattern.id), method: :get, class: "btn btn-block w-100" %>
          </button>
        </div><br>
      <% end %>
    </div>
  </div>
  
</div>