config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  
  devise_for :users,
    controllers: {
      sessions: 'users/sessions'
    }

  # get 'movies/selected_patterns'
  # get 'movies/index'
  # get 'movies/new'
  # get 'movies/edit'

  # resources :patterns do
  #   member do
  #     get 'movies/next_movies'
  #     resources :movies, except: %i(index new edit)
  #   end
  # end

  resources :patterns

  get 'movies/selected_patterns', as: :selected_patterns
  
  get 'movies/next_movies', as: :next_movies

  # get 'movies/selected_movies'
  # post 'movies/add'
  # delete 'movies/remove'
  # patch 'movies/take_out'
  # put 'movies/take_out'

  resources :movies

  post 'selected_movies/add'
  resources :selected_movies

  resources :logs

end

app/models/log.rb
class Log < ApplicationRecord
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

  # GET /resource/index
  def index

  end

  # GET /resource/index
  def show

  end

  # GET /resource/new
  def new

  end

  # POST /resource
  def create

  end

  # GET /resource/edit
  def edit

  end

  # PUT /resource
  def update

  end

  # DELETE /resource
  def destroy

  end

end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with(model: log) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
        <% log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>