config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  
  devise_for :users,
    controllers: {
      sessions: 'users/sessions'
    }

  # get 'movies/selected_patterns'
  # get 'movies/index'
  # get 'movies/new'
  # get 'movies/edit'

  # resources :patterns do
  #   member do
  #     get 'movies/next_movies'
  #     resources :movies, except: %i(index new edit)
  #   end
  # end

  resources :patterns

  get 'movies/selected_patterns', as: :selected_patterns
  
  get 'movies/next_movies', as: :next_movies

  # get 'movies/selected_movies'
  # post 'movies/add'
  # delete 'movies/remove'
  # patch 'movies/take_out'
  # put 'movies/take_out'

  resources :movies

  post 'selected_movies/add'
  resources :selected_movies

  resources :logs

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default" id="header">
  <div class="container">
    <%= link_to "面談練習アプリ", root_path, id: "logo" %>
    <nav>
      <div class="nav navbar-nav navbar-right">
        <div class="dropdown">
          <button class="dropdown-toggle" type="button" id="dropdownMenu" data-bs-toggle="dropdown" aria-expanded="false">
            管理者はこちら
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
            <% if !user_signed_in? %>
              <li><button class="dropdown-item" type="button"><%= link_to "ログイン", new_user_session_path, class: "dropdown-item" %></button></li>
            <% else %>
              <li><button class="dropdown-item" type="button"><%= link_to '面談動画一覧', movies_path, method: :get, class: "dropdown-item" %></button></li>
              <li><button class="dropdown-item" type="button"><%= link_to '面談動画選択', selected_movies_path, method: :get, class: "dropdown-item" %></button></li>
              <li><button class="dropdown-item" type="button"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %></button></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Engineer Interview App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>